GET http://localhost:3001/produtos


###
POST http://localhost:3001/produtos
content-type: application/json

{
    "nome": "Golf GTI",
    "descricao": "2.0 Turbo - Ano 2014",
    "preco": 100000
}

###
PATCH http://localhost:3001/produtos/1
content-type: application/json

{
    "nome": "Jetta GLI"
}